Assignment-03 on Numpy for AI/ML


Submitted by : Sravanthi Nandeti

RollNo : 238T1A1280

Information Technology (4th Year)

Batch : 02

### Section A : Conceptual Understanding

A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads? Mention at least two concrete reasons.

Ans:
NumPy arrays are preferred over Python lists because:
1. They provide faster numerical computations using optimized operations.
2. They use less memory because they store elements in a compact and fixed data type.




A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

Ans:
Vectorization means performing an operation on an entire NumPy array at once instead of using a Python for loop.
It matters for large datasets because vectorized operations are much faster and reduce the overhead of executing Python code repeatedly for each element




A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each. [2 Marks]

Ans:
1. A * B performs element-wise multiplication, where corresponding elements are multiplied. In neural networks, it can be used for applying a mask to activations.
2. A@ B performs matrix multiplication. In neural networks, it is used to calculate weighted sums, such as X @ W + b.




A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise.

Ans:
Broadcasting is a NumPy feature that allows arrays with different shapes to be used together in element-wise operations.
The general rule is: when comparing shapes from right to left, the dimensions must be either:
1. Equal, or
2. One of the dimensions must be 1.
If all dimensions satisfy this rule, the arrays can be combined using broadcasting.




A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why? 

Ans:
flatten() creates a new copy of the array.
ravel() returns a view whenever possible, so it generally uses less memory.

For processing large images in a memory-constrained application, I would prefer ravel() because it can avoid creating an unnecessary copy and therefore saves memory.

A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.

Ans:
For a 2D array:
axis=0 → operation is performed column-wise.
axis=1 → operation is performed row-wise

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.sum(A, axis=0) 
np.sum(A, axis=1)

array([ 6, 15])

A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

Ans:
Scaling numerical features is important because features may have different ranges, and large-valued features can dominate the model. Scaling helps many ML algorithms train more effectively.
->Normalization: Converts values to a fixed range, usually 0 to 1.
->Standardization: Converts values so that they have approximately mean = 0 and standard deviation = 1.

A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN? [2 Marks]

Answer:
np.nanmean() exists to calculate the mean while ignoring NaN (Not a Number) values.

If np.mean() is used directly on data containing NaN, the result will generally be NaN, because the missing value affects the calculation.

In [3]:
A = np.array([10, 20, np.nan, 40])
np.mean(A)
np.nanmean(A) 

np.float64(23.333333333333332)

A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

Ans:
For RGB images, each image has:
Height = 128
Width = 128
Channels = 3 (Red, Green, Blue)
For 64 RGB images, the shape is:
(64, 128, 128, 3)

A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed).

Ans:
Reproducibility means getting the same or consistent results when an experiment is repeated.
In ML, random operations are often used for data splitting, initialization, and sampling. Fixing a random seed makes these random operations repeatable.

In [5]:
rng = np.random.default_rng(42)

## Section B – Predict the Output


B1. Predict the exact output and/or resulting shape. Justify in one sentence.

Ans:
(3, 3)

Justification:
a has shape (3,) and b has shape (3,1), so NumPy broadcasting produces a 3 × 3 array.

In [6]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
print((a + b).shape)


(3, 3)


B2. Predict the output and/or shape.

Ans:
[2 5]
Shape:
(2)

Justification :

x is a 2 × 3 array, and x[:,1] selects all rows of the second column, giving [2, 5] with shape (2,).

In [7]:
x = np.arange(1, 7).reshape(2, 3)
print(x[:, 1])

[2 5]


B3. Predict the output and/or shape. 

Ans:
[10 20]
Shape:
(2)

Justification :

arr % 10 == 0 checks which elements are exactly divisible by 10, so only 10 and 20 are selected.

In [ ]:
arr = np.array([5, 10, 15, 20, 25])
print(arr[arr % 10 == 0])

[10 20]


B4. Predict the output and/or shape.

Ans:
[[10 14]
 [14 20]]
Shape:
(2, 2)

Justification :

m.T is the transpose of m, and @ performs matrix multiplication, resulting in a 2 × 2 matrix [[10,14],[14,20]].

In [9]:
m = np.array([[1, 2],
              [3, 4]])
print(m.T @ m)

[[10 14]
 [14 20]]


B5. Predict the output and/or shape.

Ans:
 nan 2.3333333333333335

 Justification:
 
np.mean() returns nan because the data contains a NaN value, while np.nanmean() ignores NaN and calculates (1 + 2 + 4) / 3 = 2.3333.

In [10]:
data = np.array([1, 2, np.nan, 4])
print(np.mean(data), np.nanmean(data))

nan 2.3333333333333335


B6. Predict the output and/or shape.

Ans :
[0 1 1]

Justification:

np.where() gives 1 when the condition x > 15 is true and 0 when it is false. Therefore, 10 → 0, 20 → 1, and 30 → 1.

In [11]:
x = np.array([10, 20, 30])
y = np.where(x > 15, 1, 0)
print(y)

[0 1 1]


B7. Predict the output and/or shape.

Ans :
2 12

Justification:

The array has shape (3,4), so it has 2 dimensions (ndim = 2) and contains 3 × 4 = 12 elements (size = 12).

In [12]:
a = np.zeros((3, 4))
print(a.ndim, a.size)

2 12


B8. Predict the output and/or shape.

Ans :
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
 
 Justification:
[::-1] reverses the rows, and the second [::-1] reverses the columns, so both the row order and column order are reversed. The resulting shape remains (3,4).

## Section C-Coding / Implementation


C1. Given a 1D NumPy array of exam scores, use np.where() to produce labels 'P' (score ≥ 40) or 'F' (score < 40).

Explanation:
np.where(condition, value_if_true, value_if_false) checks each score. If the score is 40 or above, it gives 'P'; otherwise, it gives 'F'.

In [21]:
scores = np.array([35, 45, 67, 28, 50, 39, 80])
result = np.where(scores >= 40, 'P', 'F')
print(result)

['F' 'P' 'P' 'F' 'P' 'F' 'P']


C2. Write a function standardize(x) that takes a 1D NumPy array and returns its z-score standardized version using only NumPy.

Explanation:

Standardization converts the values so that they are on a common scale. NumPy calculates the mean and standard deviation and applies the operation to all elements at once

In [22]:
def standardize(x):
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std
x = np.array([10, 20, 30, 40, 50])
result = standardize(x)
print(result)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape.

Explanation:
vstack() combines the arrays vertically, increasing the number of samples while keeping the same number of features.

In [23]:
batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])
combined = np.vstack((batch1, batch2))
print(combined)
print(combined.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

Explanation:
1. axis=0 calculates the mean and standard deviation of each column.
2. X - mean subtracts each column's mean using broadcasting.
3. / std divides each column by its standard deviation.
4. The resulting standardized matrix keeps the same shape (100, 5).

In [24]:
X = np.random.rand(100, 5)
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)
X_standardized = (X - mean) / std
print(X_standardized.shape)

(100, 5)


C5. Implement y_pred = X @ w + b for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true.

Explanation:
X @ w performs matrix multiplication to calculate the weighted values. Then b is added to get the predicted values. MSE calculates the average squared difference between the actual values (y_true) and predicted values (y_pred).

In [25]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])
w = np.array([0.5, 1.0])
b = 2
y_true = np.array([4, 7, 10])
y_pred = X @ w + b
mse = np.mean((y_true - y_pred) ** 2)
print("Predicted:", y_pred)
print("MSE:", mse)

Predicted: [ 4.5  7.5 10.5]
MSE: 0.25


C6. Using np.random.default_rng() with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.

Explanation:
size=(10,3) creates 10 samples with 3 features. Using the same seed 42 produces the same random values, so the two arrays are identical.

In [26]:
rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))
rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))
print("Shape:", data1.shape)
print("Same results:", np.array_equal(data1, data2))

Shape: (10, 3)
Same results: True


C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.

Explanation:
Min-max normalization converts the pixel values from the range 0–255 into the range 0–1. The minimum value becomes 0 and the maximum value becomes 1.

In [27]:
image = np.array([[0, 128],
                  [200, 255]])
normalized = (image - image.min()) / (image.max() - image.min())
print(normalized)

[[0.         0.50196078]
 [0.78431373 1.        ]]


C8. Given 4 RGB images of shape (28, 28, 3), stored as shape (4, 28, 28, 3), compute the average pixel value of each image across height, width and channels. State the axis argument and why.

Explanation:
axis=(1,2,3) averages the height, width, and RGB channels of each image.
So, we get one average value for each of the 4 images → shape (4,).

In [30]:
import numpy as np
images = np.random.randint(0, 256, size=(8, 18, 88, 2))
average = np.mean(images, axis=(1, 2, 3))
print(average)
print(average.shape)

[129.65088384 125.83301768 127.78314394 128.65498737 127.07481061
 127.60732323 128.84343434 127.01231061]
(8,)


### Section D – Applied / Scenario-Based Problems


D1. Data Preprocessing Pipeline.

Ans:

For data containing NaN values, we can follow these steps:
a. Detect missing values
Use np.isnan() to find the NaN values.
b. Handle missing values
Use np.nanmean() to calculate the mean while ignoring NaN, and replace missing values with the mean. This keeps the data instead of removing it.
c. Standardize the data
Calculate the mean and standard deviation using NumPy and standardize the data so that it is on a common scale.

In [31]:
x= np.array([10,20,np.nan,40,50])
print("Missing values:", np.isnan(x))
mean=np.nanmean(x)
x[np.isnan(x)]=mean
print("Clean data:", x)
mean = np.mean(x)
std=np.std(x)
x_standardized = (x-mean)/std
print("Standardized data:", x_standardized)

Missing values: [False False  True False False]
Clean data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


D2. Image Batch Understanding

1. Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

Ans:

Single image: (23, 48, 1)
23 → Height
48 → Width
1 → Channel

Batch of 8 images: (8, 23, 48, 1)
8 → Number of images
23 → Height
48 → Width
1 → Channel

Explanation:
A single image has 3 dimensions, while a batch has 4 dimensions because the first dimension represents the number of images.

2. Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

In [32]:
images =np.random.randint(0,256, size=(8,23,48,1))
print(images.shape)

(8, 23, 48, 1)


3. Compute the average image of the batch, meaning the element-wise mean across all 16 images.

In [33]:
average_image=np.mean(images, axis=0)
print(average_image.shape)

(23, 48, 1)


4. State the shape of your result and explain why.

Ans:
The result shape is:
(23, 48, 1)
Explanation:
The batch shape is (8, 23, 48, 1). Using axis=0 takes the average of the 8 images, while the height, width, and channel remain unchanged.
So:
(8, 23, 48, 1) → (23, 48, 1)
It gives one average image from the 8 images.


D3. Debug the Model Code [8 marks]
The following code contains more than one bug:

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)

w = np.array([0.5, 1.0, 0.2])  # intended weight vector

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean(y_true - y_pred ** 2)


Identify every bug. Explain, in terms of shapes and operator precedence, why each is a problem, and rewrite the corrected code.


Ans:
Bug 1: Weight vector shape is wrong
X.shape = (3,2)
w.shape = (3,)
Explaination:
X has 2 columns, so w must contain 2 weights.

w = np.array([0.5, 1.0, 0.2])
It is invalid 

The valid shape of w is : 

In [35]:
w=np.array([0.5,1.0])

Bug 2: Wrong MSE calculation

Given:
mse = np.mean(y_true - y_pred ** 2)

Here, ** has higher priority than -.

So Python calculates:

y_true - (y_pred ** 2)

But MSE needs to calculate the difference first and then square it.

In [37]:
mse=np.mean((y_true -y_pred)**2)

The Correct Code of given code is:

In [38]:
X = np.array([[1,2],
[3,4],
[5,6]])
w=np.array([0.5, 1.0])
b=2.0
y_pred=X@w+b
y_true=np.array([10,20,30])
mse=np.mean((y_true-y_pred)**2)
print("Predicted:",y_pred)
print("MSE:",mse)

Predicted: [ 4.5  7.5 10.5]
MSE: 188.91666666666666


## Section E – Bonus / Challenge


E1. Per-Column Min–Max Normalization.

Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.

In [43]:
import numpy as np
X = np.array([[70, 800],
              [80, 900],
              [90, 1000]])
min_val = X.min(axis=0)
max_val = X.max(axis=0)
X_normalized = (X - min_val) / (max_val - min_val)
print(X_normalized)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


E2. Three-Level Score Classification.

Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:
Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).

Hint: You may need to nest or combine np.where() calls.

In [46]:
import numpy as np
scores = np.array([54, 65, 70, 80, 90, 95])
result = np.where(scores < 60, "Fail",
         np.where(scores <= 90, "Average", "Excellent"))
print(result)

['Fail' 'Average' 'Average' 'Average' 'Average' 'Excellent']
